const { test, expect, _electron: electron } = require('@playwright/test');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { spawn, execFileSync } = require('node:child_process');

test('渲染、只读、多标签、另存为、重读、第二次启动及相对图片', async () => {
  const directory = await fs.mkdtemp(path.join(os.homedir(), '.pi/work/emd-ui-'));
  const fixture = path.join(directory, '阅读 示例.md');
  const sibling = path.join(directory, '第二页.md');
  const copy = path.join(directory, '副本.md');
  const markdown = '\ufeff---\r\ntitle: 样式检查\r\n---\r\n# 静心阅读\r\n\r\n熟悉的纸色，与清晰的排版。\r\n\r\n## 代码与公式\r\n\r\n```typescript\r\nconst greeting = "你好，emd";\r\n```\r\n\r\n行内公式 $E = mc^2$。\r\n\r\n$$\r\n\\int_0^1 x^2 \\, dx = \\frac{1}{3}\r\n$$\r\n\r\n> [!NOTE]\r\n> 原始 Markdown 保持只读。\r\n\r\n- [x] 已完成\r\n- [ ] 待处理\r\n\r\n:::callout 💡\r\n阅读提示\r\n:::\r\n\r\n| 功能 | 状态 |\r\n| --- | --- |\r\n| 多标签 | 支持 |\r\n\r\n## 图表\r\n\r\n```mermaid\r\nflowchart LR\r\n A[Markdown] --> B[emd] --> C[阅读]\r\n```\r\n\r\n![本地插图](<示例 图片.svg>)\r\n\r\n[打开第二页](第二页.md#另一页)\r\n\r\n<script>window.pwned = true</script><img src="bad.png" onerror="window.pwned=true"><iframe src="https://example.com"></iframe>\r\n';
  await fs.writeFile(fixture, markdown);
  await fs.writeFile(sibling, '# 另一页\n\n第二个标签页\n');
  await fs.writeFile(path.join(directory, '示例 图片.svg'), '<svg xmlns="http://www.w3.org/2000/svg" width="500" height="130"><rect width="500" height="130" rx="12" fill="#f0ebe4"/><text x="30" y="75" fill="#a45d47" font-size="28">emd · Markdown reader</text></svg>');
  const errors = [];
  let application;
  try {
    const launchEnv = { ...process.env, XDG_CONFIG_HOME: path.join(directory, 'config'), XDG_CACHE_HOME: path.join(directory, 'cache') };
    application = await electron.launch({ args: [path.resolve('.'), '--ozone-platform=x11', `--user-data-dir=${path.join(directory, 'profile')}`, fixture], env: launchEnv });
    const page = await application.firstWindow();
    page.on('pageerror', (error) => errors.push(error.message));
    await expect(page.locator('.vp-doc h1')).toHaveText('静心阅读');
    const nativeHandle = await application.evaluate(({ BrowserWindow }) => Array.from(BrowserWindow.getAllWindows()[0].getNativeWindowHandle()));
    const windowId = Buffer.from(nativeHandle).readUInt32LE();
    await expect.poll(() => /Icon \(\d+ x \d+\)/.test(execFileSync('xprop', ['-id', String(windowId), '_NET_WM_ICON'], { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 }))).toBe(true);
    await expect(page.locator('.vp-doc pre.shiki span').first()).toBeVisible();
    await expect(page.locator('.katex').first()).toBeVisible();
    await expect(page.locator('.github-alert')).toContainText('原始 Markdown');
    await expect(page.locator('.callout')).toContainText('阅读提示');
    await expect(page.locator('.task-list-item-checkbox').first()).toBeDisabled();
    await expect(page.locator('.task-list-item-checkbox').first()).toBeChecked();
    await expect(page.locator('.mermaid svg')).toBeVisible({ timeout: 60000 });
    await expect.poll(() => page.locator('img[alt="本地插图"]').evaluate((image) => image.complete && image.naturalWidth > 0)).toBe(true);
    expect(await page.evaluate(() => window.pwned)).toBeUndefined();
    expect(await page.evaluate(() => typeof window.require)).toBe('undefined');
    await expect(page.locator('.vp-doc iframe, .vp-doc script')).toHaveCount(0);
    await page.locator('.document-panel').evaluate((panel) => { panel.scrollTop = 0; });
    await expect(page.getByRole('navigation', { name: '本文目录' })).toBeVisible();
    await page.getByRole('button', { name: '折叠 静心阅读', exact: true }).click();
    await expect(page.getByRole('navigation', { name: '本文目录' }).getByRole('button', { name: '代码与公式', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '展开 静心阅读', exact: true }).click();
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(700, 650));
    await expect(page.getByRole('navigation', { name: '本文目录' })).toHaveCount(0);
    await page.getByRole('button', { name: '展开目录面板', exact: true }).click();
    await expect(page.getByRole('navigation', { name: '本文目录' })).toBeVisible();
    await page.getByRole('button', { name: '折叠目录面板', exact: true }).click();
    await expect(page.getByRole('button', { name: '展开目录面板', exact: true })).toBeVisible();
    expect(await page.locator('.app').evaluate((element) => getComputedStyle(element).borderRadius)).toBe('10px');
    await application.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1180, 850));
    await page.screenshot({ path: path.join(os.homedir(), '.pi/work/emd-light.png') });
    await expect(page.getByRole('button', { name: '最大化窗口' })).toBeVisible();
    await page.getByRole('button', { name: '最大化窗口' }).click();
    await expect(page.getByRole('button', { name: '还原窗口' })).toBeVisible();
    await page.getByRole('button', { name: '还原窗口' }).click();
    await expect(page.getByRole('button', { name: '最大化窗口' })).toBeVisible();
    expect(await application.evaluate(({ Menu }) => Menu.getApplicationMenu())).toBe(null);
    await application.evaluate(({ dialog }, destination) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: destination }); }, copy);
    await page.getByRole('button', { name: '另存为', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('已另存为');
    expect(await fs.readFile(copy)).toEqual(await fs.readFile(fixture));
    await application.evaluate(({ dialog }, source) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: source }); }, fixture);
    await page.getByRole('button', { name: '另存为', exact: true }).click();
    await expect(page.getByRole('alert')).toContainText('不能覆盖自身');
    await page.getByRole('button', { name: '关闭提示' }).click();

    await page.getByRole('link', { name: '打开第二页' }).click();
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(page.locator('.document-panel:not([hidden]) h1')).toHaveText('另一页');
    await fs.writeFile(sibling, '# 另一页\n\n已从磁盘更新\n');
    await page.getByRole('button', { name: '重新读取文件' }).click();
    await expect(page.locator('.document-panel:not([hidden]) .vp-doc')).toContainText('已从磁盘更新');
    await page.getByRole('button', { name: '查找', exact: true }).click();
    await page.getByRole('textbox', { name: '查找内容' }).fill('更新');
    await page.getByRole('button', { name: '关闭查找' }).click();
    await page.getByRole('button', { name: '关闭 第二页.md', exact: true }).click();
    await expect(page.getByRole('tab')).toHaveCount(1);
    await expect(page.getByRole('tab')).toHaveAttribute('aria-selected', 'true');
    const third = path.join(directory, '相对 路径.md');
    await fs.writeFile(third, '# 从第二次启动打开\n');
    const child = spawn(require('electron'), [path.resolve('.'), `--user-data-dir=${path.join(directory, 'profile')}`, path.basename(third)], { cwd: directory, env: launchEnv, stdio: 'pipe' });
    const code = await new Promise((resolve, reject) => { child.on('exit', resolve); child.on('error', reject); });
    expect(code).toBe(0);
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(page.locator('.document-panel:not([hidden]) h1')).toHaveText('从第二次启动打开');
    await application.evaluate(({ dialog }, source) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [source] }); }, fixture);
    await page.getByRole('button', { name: '文件', exact: true }).click();
    await page.getByRole('menuitem', { name: '打开…' }).click();
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(page.locator('.document-panel:not([hidden]) h1')).toHaveText('静心阅读');
    expect(await fs.readFile(fixture, 'utf8')).toBe(markdown);
    expect(errors).toEqual([]);
  } finally {
    if (application) await application.close();
    await fs.rm(directory, { recursive: true, force: true });
  }
});
